# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-docker-image-exists
  description: Github Action check if Docker image exists by pulling it
  homepage: https://cloudposse.com/accelerate
  topics: ""

