name: 'Docker image exists'
description: 'Check if docker image exists by pulling it'
author: hello@cloudposse.com
branding:
  icon: 'download-cloud'
  color: 'white'
inputs:
  organization:
    description: 'Organization'
    required: true
  repository:
    description: 'Repository'
    required: true
  registry:
    description: 'Docker registry'
    required: true
  tag:
    required: true
    description: "Tag"
  login:
    description: 'Docker login'
    required: false
    default: ''
  password:
    description: 'Docker password'
    required: false
    default: ''
outputs:
  image:
    description: "Docker image name"
    value: ${{ steps.context.outputs.image }}
  tag:
    description: "Docker image tag"
    value: ${{ inputs.tag }}
runs:
  using: "composite"
  steps:
    - uses: cloudposse/github-action-yaml-config-query@0.1.1
      id: context
      with:
        query: .
        config: |-
          image: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}

    - name: Login
      uses: docker/login-action@v2
      if: ${{ contains(inputs.registry, '.amazonaws.com') || ( inputs.login != '' && inputs.password != '' ) }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.login }}
        password: ${{ inputs.password }}

    - name: Pull
      id: pull
      shell: bash
      run: |
        docker pull ${{ steps.context.outputs.image }}:${{ inputs.tag }}
